version: '3.8'

# Development version of docker-compose.yml

services:
  athena:
    build: ./athena
    image: athena
    command: echo "Athena build succeeded, exiting (this is normal)"
    networks:
      - athena-network
  llm_core:
      build: ./llm_core
      depends_on:
        - athena
      image: llm_core
      command: echo "llm_core build succeeded, exiting (this is normal)"
      networks:
        - athena-network
  assessment_module_manager:
    build: ./assessment_module_manager
    depends_on:
      - athena
    ports:
      - "5100:5100"
    volumes:
      - ./assessment_module_manager/deployments.ini:/code/deployments.ini:ro
    networks:
      - athena-network
  module_example:
    hostname: module-example
    build: modules/programming/module_example
    depends_on:
      - athena
    ports:
      - "5001:5001"
    networks:
      - athena-network
  module_programming_llm:
    hostname: module-programming-llm
    build: modules/programming/module_programming_llm
    depends_on:
      - athena
      - llm_core
    ports:
      - "5002:5002"
    networks:
      - athena-network
  module_text_llm:
    hostname: module-text-llm
    build: modules/text/module_text_llm
    depends_on:
      - athena
      - llm_core
    ports:
      - "5003:5003"
    networks:
      - athena-network
  module_text_cofee:
    hostname: module-text-cofee
    build: modules/text/module_text_cofee
    depends_on:
      - athena
    ports:
      - "5004:5004"
    networks:
      - athena-network
  module_programming_themisml:
    hostname: module-programming-themisml
    build: modules/programming/module_programming_themisml
    depends_on:
      - athena
    ports:
      - "5005:5005"
    networks:
      - athena-network
  module_programming_apted:
    hostname: module-programming-apted
    build: modules/programming/module_programming_apted
    depends_on:
      - athena
    ports:
      - "5006:5006"
    networks:
      - athena-network
  module_modeling_llm:
    hostname: module-modeling-llm
    build: modules/modeling/module_modeling_llm
    depends_on:
      - athena
      - llm_core
    ports:
      - "5008:5008"
    networks:
      - athena-network
networks:
  athena-network:
    name: athena-network
    driver: bridge