# docker-compose.yaml
version: '3.8'
services:
  jenkins:
    restart: unless-stopped
    build: .
    ports:
      - 8082:8080
      # - 50000:5000
    volumes:
      - jenkins:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/run/docker:/var/run/docker
    environment:
      - JAVA_OPTS="-Dhudson.security.csrf.GlobalCrumbIssuerConfiguration.DISABLE_CSRF_PROTECTION=true"
    user: root
  # proxy:
  #   restart: unless-stopped
  #   image: nginx
  #   ports:
  #     - 80:80
  #   depends_on:
  #     - jenkins
  #   volumes:
  #     - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
volumes:
  jenkins:
